print("\n>>> CADASTRO <<<")
print("\n1-Cadastrar escola")
print("2-Listar escola")
print("3-Atualizar escola")
print("4-Deletar escola")
print("\n---------------")
print("\n5-Cadastrar turma")
print("6-Listar turma")
print("7-Atualizar turma")
print("8-Deletar escola")
print("\n---------------")
print("\n9-Cadastrar aluno")
print("10-Listar aluno")
print("11-Atualizar aluno")
print("12-Deletar aluno")
print("\n13->>SAIR<<")